### ISSUE TITLE
Upgrade `lib.eventing` to version `0.2.0`

### ISSUE THREAD

**Issue by corcoja** [boomerang-io/flow.service.listener#15]
Upgrade `lib.eventing` to version `0.2.0` for `service.listener` and `service.workflow`.

**Comment by corcoja** [comment]
PR review required for:

- boomerang-io/flow.service.listener#16
- boomerang-io/flow.service.workflow#126
- boomerang-io/charts#46

**Comment by corcoja** [comment]
@marcusdroy, @tlawrie, @morarucostel, any updates on reviewing above mentioned PRs? I would like to close these asap and start monitoring eventing in DEV env.

**Comment by tlawrie** [comment]
Hi @corcoja of course. Will start a review. We were waiting for 3.4.1 to be closed out fully.
